### ISSUE TITLE
Add Webhook receiver to Flux for Push-like experience

### ISSUE THREAD

**Issue by schnatterer** [cloudogu/gitops-playground#100]
* Add file `https://github.com/cloudogu/gitops-playground/issues/new` to `fluxv2/gitops/code/sources/main/clusters/gitops-playground/flux-system/`: 

```yaml
  # Using webhook receivers make pull-based pipelines as responsive as push-based pipelines.
  # https://fluxcd.io/flux/guides/webhook-receivers/
  ---
  apiVersion: v1
  kind: Service
  metadata:
    name: receiver
    namespace: flux-system
  spec:
    type: LoadBalancer
    selector:
      app: notification-controller
    ports:
      - name: http
        port: 80
        protocol: TCP
        targetPort: 9292
  ---
  apiVersion: notification.toolkit.fluxcd.io/v1beta1
  kind: Receiver
  metadata:
    name: scmm-receiver-flux-system
    namespace: flux-system
  spec:
    type: generic
    secretRef:
      name: webhook-token
    resources:
      - apiVersion: source.toolkit.fluxcd.io/v1beta2
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  ```
* Add ` webhook-receiver-scm.yaml` to `kustomization.yaml/` - `resources`
* Find out generated HOOK_URL: 
```shell
kubectl get receivers scmm-receiver-flux-system -o go-template --template="{{.status.url}}"
```
* On remote SCMM wait for LB to get exteranl IP 
* Add webhook to SCMM
```shell
curl $SCM_HOST/scm/api/v2/plugins/webhook/fluxv2/gitops' -X PUT -H 'Content-Type: application/json' \
   --data-raw '{"webhooks":[{"name":"SimpleWebHook","configuration":{"urlPattern":"http://$EXTERNAL_IP_OR_INTERNAL_SERVICE_NAME/$HOOK_URL","executeOnEveryCommit":false,"sendCommitData":false,"method":"AUTO"},"valid":true}]}'
```
* Create a  token. If we use a `type: generic` the token is not validated, but we need to create it, to avoid errors. So the $TOKEN value is ignored for `generic`.
   If SCMM Webhook Plugin supports setting header by then we could use [` type: gitlab`](https://fluxcd.io/flux/components/notification/receiver/#gitlab-receiver) and set the `X-Gitlab-Token` 
```
kubectl -n flux-system create secret generic webhook-token \	
--from-literal=token=$TOKEN
```

* Remove short intervals from Flux deployments
