### ISSUE TITLE
Enable alerting for fluxv2

### ISSUE THREAD

**Issue by schnatterer** [cloudogu/gitops-playground#101]
* Add to `prometheus-stack-helm-values.yaml`
```yaml
alertmanager:
  # We use alertmanager as workaround to have Flux sent alerts to mailhog, as Flux does not support SMTP
  enabled: true
  config:
    global:
      smtp_from: alertmanager-alerts@cloudogu.com
      smtp_smarthost: mailhog.monitoring.svc.cluster.local:1025
      smtp_require_tls: false
    route:
      routes:
        - receiver: 'default'
        - receiver: 'empty'
          match:
            alertname: Watchdog # Ignore watchdog here.  Comment out this route to test alerts easily.
    receivers:
    - name: 'default'
      email_configs:
      - to: alerts@cloudogu.com
        send_resolved: true
    - name: 'empty'

# Needed for #102
prometheus:
  prometheusSpec:
    # Allow for flux podmonitoris to be discoverd: https://github.com/prometheus-operator/prometheus-operator/issues/3636#issuecomment-796688902
    podMonitorSelectorNilUsesHelmValues: false
    # Use the same for serviceMonitors to be consistent
    serviceMonitorSelector: false
```
* Add file to folder `fluxv2/clusters/gitops-playground/flux-system` and add file to `kustomization.yaml`
```yaml
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Provider
metadata:
  name: alertmanager
  namespace: flux-system
spec:
  type: alertmanager
  address: http://kube-prometheus-stack-alertmanager.monitoring.svc.cluster.local:9093/api/v2/alerts/
```
* Implement a test alert such as 
```yaml
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  name: flux-reconciliation-errors
  namespace: flux-system
spec:
  providerRef:
    name: alertmanager
  eventSeverity: error
  eventSources:
    - kind: Kustomization
      name: '*'
      namespace: '*'
    - kind: HelmRelease
      name: '*'
      namespace: '*'
```

An alert can then be triggered by breaking an existing k8s resource in the `fluxv2/gitops` repo. E.g. add a syntax error to `kustomization.yaml`
