### ISSUE TITLE
Grafana Dashboards for Flux v2

### ISSUE THREAD

**Issue by schnatterer** [cloudogu/gitops-playground#102]
Add the output of those to `fluxv2/clusters/gitops-playground/flux-system` and add to `kustomization.yaml`.

```shell
flux create source git flux-monitoring \
--interval=30m \
--url=https://github.com/fluxcd/flux2 \
--namespace=monitoring \ 
--branch=main 

 flux create kustomization monitoring-config \
--interval=1h \
--prune=true \
--source=flux-monitoring \
--path="./manifests/monitoring/monitoring-config" \
--health-check-timeout=1m \
--namespace=monitoring \
--wait 
# Bases on: https://fluxcd.io/flux/guides/monitoring/
# But adds
# --namespace: PromStack seems to pick up its own namespace by default only
# And removes
# --depends-on=kube-prometheus-stack  -> Use GitOps Playground grafana
```

Also add the following to prometheus-stack `values.yaml` in order for `PodMonitor`s to be picked up by prometheus 🧐
This might have been solved in #101 
``` 
prometheus:
  prometheusSpec:
    # Allow for flux podmonitoris to be discoverd: https://github.com/prometheus-operator/prometheus-operator/issues/3636#issuecomment-796688902
    podMonitorSelectorNilUsesHelmValues: false
    # Use the same for serviceMonitors to be consistent
    serviceMonitorSelector: false
```
